env:
  secure: "ZTieiur6LmmtkVv5iyOCrVDxpMqQU03kHXDreL59T/kEXRnU3reHPOU4OY1gOsJCD8AJFfIN8ofO8+FHBwfTO5AFtdybeDpyw15gulqmcPPrTvTWCDL0bpqIS12m0fOHNW7o0Ba1mRBU8Zmpl6d1/3woF/7nCc47/VMEzV7/MX1dDKn1o5fvYi1dh/0zvHsZwiodMNtxI24IxWCEdNQpt3xDKqAJ+U4rUyqTVgPakK1JAFxEalKOYCdBz3ArvLlBXUYTCMbwpGhmxXWtNcOO/l+iUGovipaEBy8WqelSxV2Ja3FpQVjbg7gDeJpIPCNAN8wWfGA10tV8YV82wk5BGucTBC91L0H2ZzMugvQ77i5MlGdcrmcP5AnokzlA7m7mzCThyXePOxfPtchXzviAVHDu1z6sxGNhGKgyhiJbx/WGCqUJeY+R8NilPPhxTWYAXp/jCvsdU12NQI/rLlcIkdMEWi18/gcc2ePF0O1wStreo2+HR6IYAyiiO6FSHPceLyjq7F1JyUqtwvr3cIjPfjK88Kc+pgPXtyOAncU9Gn1CpbnJLJ97ZIofspv6maVtmtlpGvar0Hc4uqAqt0d7nphF31rpOtMuF0NTnsIFeftb1sxsfFhMGVnZK5UOs9GETeBKTwGbjJoiG3TURun4Bz+LIfk4sVwhYnqfqlEwPeU="
before_install:
  - gem install dpl
before_script:
  - if [[ $TRAVIS_REPO_SLUG = "mrtcode/tst" && $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST = "false" ]]; then
      dpl --provider=s3 --bucket=zoterotest1 --access-key-id=AKIAIOWX5B6F6OJJCPQA --local-dir=./ --upload-dir=_ci/client --acl=public-read;
    fi
  - unset AWS_SECRET_ACCESS_KEY
  - echo $AWS_SECRET_ACCESS_KEY
script:
  - echo $AWS_SECRET_ACCESS_KEY
  - echo $VAR1
