env:
  secure: "JiYG2GPb59ogtGyahAx7PKrqXBnN9XLgmhoqPYRPu2iHKPeaq7Ikvm+u9uuGJj2bc9jnBm5SwUn3uB3a6v9pC9SRgvVTQVAS/LnZD2DtaBOJVDB2AG3JM8KWw9hmhyVy9sL5c3zBrYC06QcPatzF89sFqDPJEGeHEx/4mo/kYMzI8/XFfXrI+LH+2CiM22SuTe0mhdhs6jKaXHNu2o6FFzM9lyObsqF72lFjb2TiNRz+isuhlgyI7yQWDNM74qyAkLE1wzDP1ktB4SSPWNWN8TyUnMWkv2/zzli7C66/bVMCOvy19G7XtWe22mBjEETXR+q+UXpfJ9h/9yunpPRue82JUre6fQ8K0sY7KkGdgnSLIpnC7y69zrPEyr0dx9eSJNQebfZJLXk7xgmIBB/4DosGAQzJ6PudGnFHLZ62zvXbtTGlIhkOEmi2CCClc89I4YYKOU1wavKbdok7IgLvNoBlF80tuWzgGDBgfdmc5gwH+t/ZueIgPXGHpdt1cEec2JiefKjmjrSixFJhIJIviIejxU1fExvWsycN5viT+tiaRas5vQJaHhchuKAWePbEX+aZmnDd+5BdR6PJYg6Hd806B10H8G8TVs6LnzOczkpf3/dddvFsLrEZ0p/xc92i1V4ImmrQK1a7qdxBrWyBq6l4zJyPm1PjhGNdHLeOxSc="
before_install:
  - echo $VAR1
  - echo $AWS_SECRET_ACCESS
  - unset VAR1
  - echo $VAR1
before_script:
  - echo $VAR1
script:
  - echo $VAR1
