env:
  global
    - VAR1=asdfasdf
    - secure: CHRqLk/Ze4oDzxgmZjhLDw7ArFqHN67+7vgnQOqEuHwXUmAHXzo/l5VijpA4lFVTMetwbQ0lHfSre8WPpA9/1G6pHi6K41wsxhYHGfZRsml8ru+mLEyTIqKa9BWC7fa8Wfy6mNlw4wzbabbhd9eRYYqHfdMFg/0MHQe4mfmfKR9j6z0IWe0w7mmoVhFTcmXrBrY6op70GHYnLcbTBb3BaRYzMMY+dEOJBRV1+6J5XBzYlAa9cUWFnKfGRn2OeoZ4FWmIheP9ak3jdZ51CIi9dlJ2oRkBK8iwHNmghAXfwExVQKAcAdOLW5H4rQi69ShCL38y4khf8pw2im0qtn39Yc3BH65Z/KQrqGj+3fJZx36jF1IvPvo+gn9EC4fpvYsqBXeByVL6Y+jXyEpiEGPpo+B0g/TeCOzVROpWGGNgg1yA8SXGaB9CQ1dK0+Y0hfFBGtSO56SgR06WsbqmA5reB9BDykUMo2BO4YkXiWmuvWIPCaZdhe0L7PYQ82a7TNAYsgiI7oiI5vUb2VCn13aS5JaJJzWGwjd3uDUBW5yBrrve1By1DpA46YfguqPKJBTnEXGPlgdjpq46/Epma9LC0SghmRoiqDAsAU6NC27lp1N2SoCTUvjjpUCVOL9CBinkpZ7F9gJfXceOt2G/0ceaAF5McBUQS7NLAtswx7Y/UVM=
before_install:
  - echo $VAR1
  - echo $AWS_SECRET_ACCESS
  - unset VAR1
  - echo $VAR1
before_script:
  - echo $VAR1
script:
  - echo $VAR1
