env:

sudo: required
dist: trusty
language: node_js
node_js:
- '8'
cache:
  timeout: 2000
  directories:
  - data
before_install:
- cd data
- df -h
- ls -la
- |
  if [ -r ~/.cache/pip ]
  then
    find ~/.cache/pip -type f
    du -hs ~/.cache/pip
  fi
