env:

sudo: required

cache:
  timeout: 2000
  directories:
    - data

before_install:
  - cd data
  - ls -la
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - ls -la
