env:
  secure: "A0OU3eeVlNvM2kjgzhy6PyzIvAc0KGKcHOML6FvS8wdAlaYS3ugAgMy8OHZjOWfqgH3AVK0B0MXqouENV3IYSZbhLKod4S/lAUJ0X/QP+iqIxmY98DmJJZ4KXWDkbDbsEBC482wWYiK9sFAxnmjgsu8+IRxy7R7roOBEDoMf36XAo7xcrqEfyAnCD6nzZ0oBbycaUzmZMaGsNNuvdbXEBqRXHQdZ1CYz8E5+j7JsrgtkPAqce0c0TaAFhpYp8yjRKRrVLiGgkSRfUmBPDqVV6YR5rOX1YZX/NQgVxwtynKAarfVJuDQ29euIBNjsPONJPllbVrC8chs+SqWLlo4o+GD5qjKp2DIcmvxSNEA8aM0L8Oh56ZZrPTorwDzKVF9vn9sb2dHwPhk9LZ/GHdMJZutpnIMR1alnpHfE2MmyzSXFSwLM97ddclbyVuHn1G2jFgmcNikUKpCfi0TXGNM2d9uzPNvxv2lk2tPXHAawX7wKjn8gvk0n4rKUgc0ugggmcEJterP8OBnd17Buhw8JljBc302PD7RAwIoSfBJas5rryDVi1W0jJnxF5nKDZFB78ijpkphpPQwpSsR2x+mkmZn3Glv83KzakYq7bXxDcBVL5SoBGfl9JSBV9vvLampdlGTm/KLsGL1Y8rxCIA+ZCs0yVJs2ZcFVWNv6tagKm90="
before_install:
  - gem install dpl
before_script:
  - if [ $FX_VERSION = "45.0.2esr" ]; then
      wget -O tarball "https://archive.mozilla.org/pub/firefox/releases/45.0.2esr/linux-x86_64/en-US/firefox-45.0.2esr.tar.bz2";
    fi
  - if [ $TRAVIS_REPO_SLUG = "mrtcode/tst" && $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
      dpl --provider=s3 --bucket=zotero-download --access-key-id=AKIAJFDVJ54MCAEXPQ5Q --local-dir=build-zip --upload-dir=ci/client --acl=public-read;
    fi
script:
  - echo $VAR1
