env:

sudo: required
dist: trusty

language: node_js

node_js:
  - "8"

cache:
  timeout: 2000
  directories:
    - data

before_install:
  - cd data
  - ls -la
  - df -h
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - wget http://ubuntu-release.mirror.serveriai.lt/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
  - ls -la