env:

sudo: required
dist: trusty
language: shell

cache:
  timeout: 2000
  directories:
  - data
before_install:
- df -h
- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo apt-get install -y build-essential
- cd data
- df -h
- ls -la
- du -hs ~/.cache/
- du -hs ~/.casher/

